### ISSUE TITLE
Ensure users know how to contribute edits to each page

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/website#122] opened 2021-03-24 14:55 UTC
Since we draw from different sources, "edit this page" should link to the correct file in the correct repo. Example component CRDs are from the go code in each separate controller, which would be very difficult for new users to find.

**Comment by hiddeco** [comment] 2021-03-24 15:10
Pages that are sourced from other repositories do not have an edit button in the sidebar, see for example: https://deploy-preview-110--fluxcd.netlify.app/docs/components/image/imageupdateautomations/

**Comment by hiddeco** [comment] 2021-03-24 15:11
Also, duplicate of #121?

**Comment by dholbach** [comment] 2021-03-26 07:17
Closing as duplicate.

**Closed by dholbach** 2021-03-26 07:17 UTC
